#!/bin/bash

session=$1

if [[ ! -f ~/.tmux/tmux-$session ]]; then
    tmux new-session -s $session
else
    ~/.tmux/tmux-$session
fi

if [[ -n $TMUX ]]; then
    tmux switch-client -t $session
else
    tmux attach-session -t $session
fi
